### ISSUE TITLE
[Bug]: Cannot add friend

### ISSUE THREAD

**Issue by BigYass** [spnda/BlockProt#219]
### Version of BlockProt

1.4.4

### Description of the bug

When entering the Lock iventory screen and trying to search for a friend, clicking the map item. I can take it like it is a normal inventory. In the console I get a null exeption at InvetoryEventListener.java at line 61, at FriendManageInvetory.java line 121, at FreubdSearchInventory.java line 125. Wonder if it will be fixed, also why does the variable are all objects in some function like var curPlayer ?

### Steps to reproduce

1. Go to the lock screen of a chest
2. Click on the player head
3. Click on the map and it doesn't works at least on my side

### Additional context

My plugin is translated to french, I don't know if it changes anything

**Comment by spnda** [comment]
what Minecraft version and server software is this (also version 1.4.4 of the plugin is not a thing?) The map uses highly version dependant code and will not magically work with newer versions  of the game.

**Comment by BigYass** [comment]
I use spigot latest version for minecraft 1.19.4. maybe that's why however you code doesn't seem to use nms ?

**Comment by spnda** [comment]
It's not my code that uses NMS but AnvilGUI. And AnvilGUI does support 1.19.4, so perhaps its some weird build of yours where it doesn't detect that its 1.19.4? Whats the /version output?

**Comment by BigYass** [comment]
[Fri 17:10:13 INFO ] This server is running CraftBukkit version 3741-Spigot-d1bd3bd-ccbc6ab (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
  [Fri 17:10:13 INFO ] Checking version, please wait...
  [Fri 17:10:13 INFO ] You are 2 version(s) behind
  
  Here is the output. Do you think you make a support for newer version, if not can you explain how I can fix it ?

**Comment by spnda** [comment]
This version of *Spigot* should definitely supported. However, I'm kinda confused why (1) you're running CraftBukkit (please use Spigot for the love of god) and (2) why my plugin didn't disable itself because youre running CraftBukkit. I don't think it should have an impact on this exact feature, but half of your things are not gonna work correctly because you're using CraftBukkit.

**Comment by nscode** [comment]
Hi. I have ran into the same issue on a paper 1.20.1 server

The rest of the features of the addon works but when clicking search players we just pickup the map

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R1" [in thread "Server thread"]
        at de.sean.blockprot.bukkit.shaded.anvilgui.version.VersionMatcher.match(VersionMatcher.java:34) ~[blockprot-spigot-1.1.10-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:39) ~[blockprot-spigot-1.1.10-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:558) ~[blockprot-spigot-1.1.10-all.jar:?]
        at de.sean.blockprot.bukkit.inventories.FriendSearchInventory.openAnvilInventory(FriendSearchInventory.java:41) ~[blockprot-spigot-1.1.10-all.jar:?]
        at de.sean.blockprot.bukkit.inventories.FriendManageInventory.onClick(FriendManageInventory.java:126) ~[blockprot-spigot-1.1.10-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryClick(InventoryEventListener.java:61) ~[blockprot-spigot-1.1.10-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-83]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-83]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-83]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3205) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-83]
```

**Comment by DawnStorm2** [comment]
I have come across the same issue as Nscode

**Comment by spnda** [comment]
> Hi. I have ran into the same issue on a paper 1.20.1 server
> 
> The rest of the features of the addon works but when clicking search players we just pickup the map
> 
> ```
> Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R1" [in thread "Server thread"]
>         at de.sean.blockprot.bukkit.shaded.anvilgui.version.VersionMatcher.match(VersionMatcher.java:34) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:39) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:558) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at de.sean.blockprot.bukkit.inventories.FriendSearchInventory.openAnvilInventory(FriendSearchInventory.java:41) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at de.sean.blockprot.bukkit.inventories.FriendManageInventory.onClick(FriendManageInventory.java:126) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryClick(InventoryEventListener.java:61) ~[blockprot-spigot-1.1.10-all.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-83]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-83]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-83]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3205) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
>         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
>         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-83]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-83]
> ```

The error message is pretty descriptive. The version of the plugin you have installed doesn't support 1.20. You're using 1.1.10, while 1.1.12 is already released. Please upgrade to a newer version that supports 1.20. Thanks. Same for @DawnStorm2.

**Comment by nscode** [comment]
Sorry in retrospect its obvious. As i had downloaded the plugin today i got tripped up. Fyi the version at https://hangar.papermc.io/spnda/BlockProt is out of date then

**Comment by spnda** [comment]
Wow thanks, I completely forgot I uploaded my plugin onto Hangar. I just updated the plugin there too.

**Comment by nscode** [comment]
No worries. Thanks for the mod!

**Comment by Kingwersens** [comment]
This is still a problem for me. Im running paper 1.20.2 (Not sure if its that the plugin dosent support Minecraft 1.20.2) 
The version of the plugin im using is 1.1.13 (The newest i could find)

**Comment by spnda** [comment]
> This is still a problem for me. Im running paper 1.20.2 (Not sure if its that the plugin dosent support Minecraft 1.20.2) The version of the plugin im using is 1.1.13 (The newest i could find)

No this was a new issue that's already fixed but I haven't had time to update the plugin yet on curseforge/modrinth...

**Comment by Kingwersens** [comment]
So what can i do to solve it? Change version?

**Comment by spnda** [comment]
I'll update it now. The updated version is also on the Discord if you want to quickly join that.
